# Generated by Django 5.2.10 on 2026-01-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_order_discount_amount_order_items_snapshot_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShippingAddress",
        ),
    ]
